### ISSUE TITLE
Problem getting the dataset

### ISSUE THREAD

**Issue by EdwinHernandezG** [imaris/imglib2-imaris-bridge#1]
First of all, thanks a lot for the bridge. This would save a lot of time in our analysis pipelines.

Today I was trying to get a dataset from Imaris to Fiji, but I got the following error.

```
>>> app = imaris.getApplication()
com.bitplane.xt.DefaultImarisApplication@23df173e
>>>  dataset = app.getDataset()
java.lang.NoClassDefFoundError: net/imglib2/cache/img/optional/CellDimensionsOptions
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at java.beans.Introspector.getPublicDeclaredMethods(Introspector.java:1336)
	at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1197)
	at java.beans.Introspector.getBeanInfo(Introspector.java:426)
	at java.beans.Introspector.getBeanInfo(Introspector.java:173)
	at groovy.lang.MetaClassImpl.lambda$addProperties$4(MetaClassImpl.java:3409)
	at java.security.AccessController.doPrivileged(Native Method)
	at groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:3409)
	at groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:3390)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:273)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:315)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:325)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:262)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:981)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createPojoSite(CallSiteArray.java:116)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallSite(CallSiteArray.java:160)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at Script2.run(Script2.groovy:1)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:303)
	at org.scijava.plugins.scripting.groovy.GroovyCompiledScript.eval(GroovyCompiledScript.java:58)
	at javax.script.CompiledScript.eval(CompiledScript.java:106)
	at org.scijava.script.DefaultScriptInterpreter.interpret(DefaultScriptInterpreter.java:218)
	at org.scijava.script.ScriptREPL.evaluate(ScriptREPL.java:197)
	at org.scijava.ui.swing.script.PromptPane.lambda$execute$1(PromptPane.java:171)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$1(DefaultThreadService.java:211)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: net.imglib2.cache.img.optional.CellDimensionsOptions
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more
```

Any idea how I can solve it?

Thanks for your help

**Comment by tpietzsch** [comment]
Hmm... the class `net.imglib2.cache.img.optional.CellDimensionsOptions` is in imglib2-cache since a few versions.
An up-to-date Fiji should have the most current version `imglib2-cache-1.0.0-beta-16.jar`.

Could you verify which version of the `imglib2-cache-...jar` you have in `Fiji.app/jars/`? Maybe you have an update site enable that (erroneously) ships an older version? (If so, that would be good to know so that we can fix that update site...)

**Comment by EdwinHernandezG** [comment]
You are right.

I have the `imglib2-cache-1.0.0-beta-13` version. According to my updater is the update site is Sciview.

**Comment by tpietzsch** [comment]
Thanks! So if you disable that update site temporarily or in a different Fiji copy it should hopefully work.

**Comment by EdwinHernandezG** [comment]
Perfect, it is working now. Thanks a lot!
